version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: relayer
    ports:
      - 3306:3306
    volumes:
      - ./data/mysql/data:/var/lib/mysql
    command:
      #      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
    privileged: true
    restart: always
  relayer:
    build:
      context: ../../
      dockerfile: Dockerfile
      args:
        PACKAGE: relayer
    container_name: relayer
    restart: always
    volumes:
      - ./.env:/app/.env
    ports:
      - 4101:4101
      - 6061:6061
    working_dir: /app
    depends_on:
      - mysql
    entrypoint:
      relayer
